server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://116.205.180.54:3306/blockchain
    username: root
    password: ZHMzhm456654
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://bitcoin:Cu1gu0dltdz@116.205.180.54/bitcoin

coisini:
  security:
    jwt-key: coisini
    # 过期时间
    token-expired-in: 86400000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false